### ISSUE TITLE
kubeconfig requirements and limitations in roles

### ISSUE THREAD

**Issue by tonyskapunk** [redhatci/ansible-collection-redhatci-ocp#296]
Opening this issue to discuss and understand the limitations/requirements on kubeconfig for k8s related roles.

### Problem

It has been expressed that some environments have limitations on the use of ENV variables, preventing them to use roles that require  KUBECONFIG ENV var to be used in a role.

### Proposal

We would like to use this issue to understand any kind of limitation or requirement on the use of k8s related roles to make them more accessible to all. Please document any limitation/requirement in this issue.

---

cc: @sshnaidm

**Comment by lack** [comment]
Given that we'll probably often be using `community.kubernetes` or one day `kubernetes.core`, we should come up with some idiom that makes it easy for our roles to use that collection, and it may be prudent to make sure our way of receiving credentials matches the various ways that collection works.

In the sideload_kernel role, for example, I came up with this:
- https://github.com/redhatci/ansible-collection-redhatci-ocp/blob/main/roles/sideload_kernel/README.md#authentication

Basically my role expects a variable called `k8s_auth` which is expected to be a dictionary whith values that correspond to the individual environment variables that the underlying `community.kubernetes` collection expects.

The reason for this kind of design is that it is hard to pass environment variables directly to roles, but not hard for a role to take a variable and put it in the environment any time we call into that collection.  For an example, see this:
- https://github.com/redhatci/ansible-collection-redhatci-ocp/blob/main/roles/sideload_kernel/tasks/main.yml#L7-L13

**Comment by tonyskapunk** [comment]
> The reason for this kind of design is that it is hard to pass environment variables directly to roles, but not hard for a role to take a variable and put it in the environment any time we call into that collection.

It is possible to pass ENV to a role. I found it is the same amount of effort to *define* ENV or var in a role, but I see some advantages with the ENV.

As a variable:
```yaml {.numberLines}
- name: Role Foo
  vars:
    k8s_auth:
      K8S_AUTH_KUBECONFIG: /var/lib/clusterauth/kubeconfig
  ansible.builtin.include_role:
    name: redhatci.ocp.foo
```

It requires all the task that rely on the variable to use `environment: "{{ k8s_auth }}"`

As an environment variable:

```yaml
- name: Role Foo
  ansible.builtin.include_role:
    name: redhatci.ocp.foo
    apply:
      environment:
        K8S_AUTH_KUBECONFIG: /var/lib/clusterauth/kubeconfig
```

No need to define `environment:` on each task.

**Comment by sshnaidm** [comment]
I'd avoid as possible all environment related stuff, since it wasn't supported historically on all modules and supposed to work mostly for shell/command stuff. More Ansible-like way is to specify explicit variables and use them in a [defined precedence](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#understanding-variable-precedence), what is good for bash is not always good for Ansible.
The way I would see it working is:
1. To have an explicit kubeconfig variable for each role separately, which will give a flexibility to use same role in same playbook for different clusters, for example guest cluster on HCP.
    * for example role `acm_setup` has `acm_setup_kubeconfig: ...`, role `hcp_install` has `hcp_install_kubeconfig` etc.
    * in this case if you run all roles for one cluster only, just define the same variable in playbook for kubeconfig and pass it to all roles.
``` yaml
- hosts: localhost
  vars:
    my_only_kubeconfig: /var/lib/kube...
  tasks:

    - name: Role Foo
      ansible.builtin.include_role:
        name: redhatci.ocp.acm_setup
      vars:
        acm_setup_kubeconfig: "{{ my_only_kubeconfig }}"
```
and different kubeconfigs:
```yaml
- hosts: localhost
  tasks:

    - name: Role Foo
      ansible.builtin.include_role:
        name: redhatci.ocp.hcp_install
      vars:
        hcp_install_kubeconfig: "{{ host_kubeconfig }}"

    - name: Role Foo
      ansible.builtin.include_role:
        name: redhatci.ocp.something_else
      vars:
        something_else_kubeconfig: "{{ guest_kubeconfig }}"

```

2. When you use environment variables you don't have control on what's going on. Env vars can be set in shell where you run Ansible, can be set in shell on your controller host, or can be NOT set there. The can come from bashrc, defaults in bash defaults on a machine, they can change by users easily etc etc. It's not an Ansible thing, it's a bash thing. And when you don't control thing you have a bigger chance to run something wrong or on wrong cluster and it opens doors for more breakages. Explicit setting variables gives you a controlled and it means reliable environment. I would eliminate all env var usages in roles and define them as a bad practice.
3.  While it's still there we can avoid breaking current code by discovering variable before in tasks and set if our `*_kubeconfig` arguments are empty or not defined. For example:
```yaml
- set_fact:
    env_kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"

- name: Kubernetes task
  kuberneres.core.k8s:
    kubeconfig: "{{ hcp_install_kubeconfig | default(env_kubeconfig, true) }}"
    ....
```
while `true` in `default` will cover an empty `hcp_install_kubeconfig` as well.
This way people can continue to use current code while we can set a deprecation message or whatever and change it in future.

**Comment by sshnaidm** [comment]
Please see the patch for olm operator role: #305

**Comment by lack** [comment]
I just went back to the docs for https://galaxy.ansible.com/ui/repo/published/kubernetes/core/content/module/k8s/ and I'm scratching my head to figure out why I even had to use the environment at all - I see that most of the roles there accept a `kubeconfig` variable which would be the path to the kubeconfig file - No environment needed at all.

So given that we can just pass variables around and not need the environment, the question would be whether we need to support alternate authentication mechanisms or just `kubeconfig`...  The underlying mechanisms support a bunch of other ways, like URI+username+password or URI+token...

**Comment by thekad** [comment]
> 2. When you use environment variables you don't have control on what's going on. Env vars can be set in shell where you run Ansible, can be set in shell on your controller host, or can be NOT set there. The can come from bashrc, defaults in bash defaults on a machine, they can change by users easily etc etc. It's not an Ansible thing, it's a bash thing. And when you don't control thing you have a bigger chance to run something wrong or on wrong cluster and it opens doors for more breakages. Explicit setting variables gives you a controlled and it means reliable environment. I would eliminate all env var usages in roles and define them as a bad practice.

Except that's not what is happening here? we're not relying on environment variables to exist, we're asking you to explicitly set the environment variable to fit your use case when including the role, which is (in the case of KUBECONFIG) a standard env var used everywhere in the k8s ecosystem. It is true you can munge the env var in a script and cause unintended side effects, just the same if you munge the path to the provided kubeconfig file.

Having a kubeconfig extra variable on every role that uses the *.k8s modules provides no benefit in the majority of the cases, I can only see it being useful when your role is expected to work with several different KC files, in which case you'd adjust that 1 role to accept X number of KC file paths.

**Comment by sshnaidm** [comment]
@thekad my point is that environment variables is not "ansible way" to put variables, because they can easily be changed outside of Ansible, and not controlled by it. Setting env var in playbook is hack-ish and should not be used in a regular deployments. Env vars are for shell, not for Ansible. Actually I think I pretty much covered it in my response above.
Providing kubeconfig is an Ansible way and allows strict control and configuration for each task in each role, what we want to achieve usually. In addition it allows not only your team to use this role, but any other what is actually the purpose of this repository if I understand correctly, @fredericlepied ?
Using KUBECONFIG is good for bash, but not so generally spread as in your code, for example in Ansible modules there is another env var that controls kubeconfig - [`K8S_AUTH_KUBECONFIG`](https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_module.html#parameter-kubeconfig), so we enter here the door of hell of env vars. :smiley: 
And exactly like you mentioned it allows to provide different kubeconfigs for different roles, what is very common in our workflows and is actually a side-effect of a good planned and designed Ansible code with enough flexibility to be used by various groups and for various use cases.

**Comment by nsilla** [comment]
For further information, [this is a PR @sshnaidm created to implement his view of how to handle the k8s credentials](https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/305).
The good thing of this approach is that it allows for both, passing the credentials as an Ansible variable and as an env var.
The change looks compatible with the DCI tools, so it'd be a matter of agreeing on whether we should keep the roles for as many use cases as possible or if it's better to agree on a limited set of good practices.

**Comment by tonyskapunk** [comment]
> 1. To have an explicit kubeconfig variable for each role separately, which will give a flexibility to use same role in same playbook for different clusters, for example guest cluster on HCP. 

Sorry, but I'm not seeing how flexibility is added through variables and not with ENV vars, they seem to me equally flexible, in both cases the playbook consuming a role specifies the variable to use in the role.

This is an example as yours, but with ENV vars, in both cases the playbook has the control of what variable is going, without the need to specify every single task in the role to use `kubeconfig`.

```yaml
- hosts: localhost
  tasks:

    - name: Role Foo
      ansible.builtin.include_role:
        name: redhatci.ocp.hcp_install
      apply:
        environment:
          KUBECONFIG: "{{ host_kubeconfig }}"

    - name: Role Foo
      ansible.builtin.include_role:
        name: redhatci.ocp.something_else
      apply:
        environment:
          KUBECONFIG: "{{ guest_kubeconfig }}"
```

> 2. When you use environment variables you don't have control on what's going on.

I think the above proves that you have control on the ENV vars that **you care**, granted you might not control all of them, but is not about random or uncontrolled vars, is about those you know your role requires or uses.

> 3. While it's still there we can avoid breaking current code by discovering variable before in tasks and set if our *_kubeconfig

This is the beauty about using this particular env var, you avoid repeating yourself as this is done by the [lib](https://github.com/kubernetes-client/python/blob/release-29.0/kubernetes/base/config/kube_config.py#L48) used by the k8s modules.

Additionally, as @thekad mentioned the advantage of `KUBECONFIG` is to be consumed by the k8s ecosystem, specifically tooling.

What I would like to understand better is how this ENV approach limits your use cases, do you have a concrete example where the current implementation of the roles are not allowing your to consume them? Can we narrow to a specific role? For instance `olm_operator`?

Thanks!
