### ISSUE TITLE
Normal update mandatory parameters for container certification project failed to validate-cert-setting

### ISSUE THREAD

**Issue by ansvu** [redhatci/ansible-collection-redhatci-ocp#482]
### Bug Summary

The issue occurred when testing with normal create and update container certification project and it failed to validate  `validate_cert_settings` before updating the mandatory settings to update the cert-project. Because I had updated this file [validate_cert_settings](https://github.com/redhatci/ansible-collection-redhatci-ocp/blob/main/roles/create_certification_project/tasks/validate_cert_settings.yml) to adapt the [create_cert_projects_loop](https://github.com/redhatci/ansible-collection-redhatci-ocp/blob/main/roles/preflight/tasks/create_cert_projects_loop.yml)  to make it works with parallel feature but I did not test the normal create container and update settings use-case. 

### Details

The issue for this issue triggered because I had removed the following task from this file [validate_cert_settings](https://github.com/redhatci/ansible-collection-redhatci-ocp/blob/main/roles/create_certification_project/tasks/validate_cert_settings.yml) 

```yaml
- name: Validate cert_settings for container project
  ansible.builtin.assert:
    that: "{{ item }} is defined"
    fail_msg: "The parameter {{ item }} is required to update cert project"
    success_msg: "The parameter {{ item }} is present"
  with_items:
    - cert_item.short_description
    - cert_item.short_description | length >= 50
    - cert_settings.auto_publish
    - cert_settings.email_address
    - cert_settings.build_categories
    - cert_settings.registry_override_instruct
    - cert_settings.application_categories
    - cert_settings.os_content_type
    - cert_settings.privileged
    - cert_settings.release_category
    - cert_settings.repository_description
  when: product_type == 'container'
```
And replaced with this to adapt with `create_cert_projects_loop.yml` for parallelization PR342

```yaml
---
- name: Validate cert_settings for container project
  ansible.builtin.assert:
    that:
      - "operator.short_description is defined"
      - "operator.short_description | length >= 50"
      - "cert_settings.auto_publish is defined"
      - "cert_settings.email_address is defined"
      - "cert_settings.build_categories is defined"
      - "cert_settings.registry_override_instruct is defined"
      - "cert_settings.application_categories is defined"
      - "cert_settings.os_content_type is defined"
      - "cert_settings.privileged is defined"
      - "cert_settings.release_category is defined"
      - "cert_settings.repository_description is defined"
    fail_msg: "The parameter {{ item }} is required to update cert project"
    success_msg: "The parameter {{ item }} is present"
  when: product_type == 'container'
```

It's my bad I did not test the normal use-case for create and update container certification project.  And it failed at the validation the `cert-settings` especially the complex nested variable `cert_item`. 

The reason for creating container-cert-in-loop is to save these projects then run the preflight check-container in parallel. 

One quick-fix for this issue is to update this file [validate_cert_settings](https://github.com/redhatci/ansible-collection-redhatci-ocp/blob/main/roles/create_certification_project/tasks/validate_cert_settings.yml)  as following:

```yaml
---
- name: Validate cert_settings for container project creation in-loop
  ansible.builtin.assert:
    that:
      - "operator.short_description is defined"
      - "operator.short_description | length >= 50"
      - "cert_settings.auto_publish is defined"
      - "cert_settings.email_address is defined"
      - "cert_settings.build_categories is defined"
      - "cert_settings.registry_override_instruct is defined"
      - "cert_settings.application_categories is defined"
      - "cert_settings.os_content_type is defined"
      - "cert_settings.privileged is defined"
      - "cert_settings.release_category is defined"
      - "cert_settings.repository_description is defined"
    fail_msg: "The parameter {{ item }} is required to update cert project"
    success_msg: "The parameter {{ item }} is present"
  when:
    - product_type == 'container'
    - do_container_parallel_test

- name: Validate cert_settings for container project
  ansible.builtin.assert:
    that: "{{ item }} is defined"
    fail_msg: "The parameter {{ item }} is required to update cert project"
    success_msg: "The parameter {{ item }} is present"
  with_items:
    - cert_item.short_description
    - cert_item.short_description | length >= 50
    - cert_settings.auto_publish
    - cert_settings.email_address
    - cert_settings.build_categories
    - cert_settings.registry_override_instruct
    - cert_settings.application_categories
    - cert_settings.os_content_type
    - cert_settings.privileged
    - cert_settings.release_category
    - cert_settings.repository_description
  when:
    - product_type == 'container'
    - do_container_parallel_test == false
```

And I had tested directly and locally for both normal and parallel use-cases to create,update,attach and submit, and it works fine. Here is the working-logs for [normal-use-case](https://www.distributed-ci.io/jobs/bf65f36e-0641-4e52-986e-f18e98528c25/jobStates) and [parallel-create-container-in-loop](https://www.distributed-ci.io/jobs/25b42a3d-c0e0-4dd2-a9e6-ee52116a1779/jobStates)

@tkrishtop please review the solution I suggested above (it's not pretty), but I am really want you to review this file again [create_cert_projects_loop](https://github.com/redhatci/ansible-collection-redhatci-ocp/blob/main/roles/preflight/tasks/create_cert_projects_loop.yml). It seems `cert_item` reached this template `update_project_container.json.j2` but not able to pass-thru the `validate_cert_settings`.  

For CI job logs from failing to validate the cert-settings for normal creation of certification project is shared here [error-log](https://www.distributed-ci.io/jobs/5703bd1b-d426-4823-8c86-f9f91140ead7/jobStates)

Pipeline-settings, you can get from from slack's discussion.
